export const IOC_TYPE = {
  AUTH_PERSISTED_DATA_ITEM: Symbol('AUTH_PERSISTED_DATA_STORE'),
  TOASTR: Symbol('TOASTR'),
  LOGGER_FACTORY: Symbol('LOGGER_FACTORY'),
  TRANSLATION_FUNCTION: Symbol('TRANSLATION_FUNCTION'),
  CONFIG: Symbol('CONFIG'),
  API_SERVICE_FACTORY: Symbol('API_SERVICE_FACTORY'),
  STORE: Symbol('STORE'),
  REDUCER: Symbol('REDUCER'),
  DISPATCHER: Symbol('DISPATCHER'),
  EVENT_EMITTER: Symbol('EVENT_EMITTER'),
  ACTION_LOGIC: Symbol('ACTION_LOGIC')
};
