export const IOC_TYPES = {
  TRANSLATION_FUNCTION: Symbol('TRANSLATION_FUNCTION'),
  CONFIG: Symbol('CONFIG'),
  API_SERVICE: Symbol('API_SERVICE'),
  STORE: Symbol('STORE'),
  REDUCER: Symbol('REDUCER'),
  DISPATCHER: Symbol('DISPATCHER'),
  EVENT_EMITTER: Symbol('EVENT_EMITTER'),
  ACTION_LOGIC: Symbol('ACTION_LOGIC')
};
